services:
  db:
    container_name: watchlistdb
    build: ./db
    networks:
      - private
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: watchlist
  api:
    container_name: watchlistapi
    build: ./api
    volumes:
      - './api:/app/api'
      - '/api/node_modules'
    networks:
      - private
    ports:
      - 3070:3070
    environment:
      DB_HOSTNAME: db
    depends_on:
     - db
  ui:
    container_name: watchlistui
    build: 
      context: ./ui
      args: 
        REACT_APP_TARGET: api
    volumes:
      - './ui:/app/ui'
      - '/ui/node_modules'
    networks:
      - public
      - private
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api


networks:
  public:
  private: