services:
  db:
    container_name: watchlistdb
    image: br0k3n/watchlistdb:main
    networks:
      - private
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: watchlist
  api:
    container_name: watchlistapi
    image: br0k3n/watchlistapi:main
    volumes:
      - './api:/app/api'
      - '/api/node_modules'
    networks:
      - private
    ports:
      - 3070:3070
    environment:
      DB_HOSTNAME: db
    depends_on:
     - db
  ui:
    container_name: watchlistui
    image: br0k3n/watchlistui:main
    volumes:
      - './ui:/app/ui'
      - '/ui/node_modules'
    networks:
      - public
      - private
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api


networks:
  public:
  private: