name: Integration Tests CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Start containers
      run: docker build ./db -t watchlistplus-db:latest

    - run: docker run -d -e POSTGRES_PASSWORD=password -e POSTGRES_DB=watchlist -p 5432:5432 watchlistplus-db

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '18.14'
        cache: 'npm'
        cache-dependency-path: ./api/package-lock.json

    - name: ci
      run: npm ci
      working-directory: ./api

    - name: run tests
      run: npm run test:integration
      working-directory: ./api