name: Integration Tests CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Run tests
      run: docker container exec watchlistapi npm run test:integration
      working-directory: ./api

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down