on:
  workflow_dispatch:

jobs:
  artillery:
    name: Load test
    runs-on: ubuntu-latest
    container: artilleryio/artillery:latest
    steps:
      - uses: actions/checkout@v3

      - name: Start containers
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"

      - name: Execute load test
        run: /home/node/artillery/bin/run run ./api/load test/script.yml